### ISSUE TITLE
[質問]Basic認証の場合の対応

### ISSUE THREAD

**Issue by unicode45** [advancedbear/EPGStation-Notifier#3]
お世話になります。
偶然存在を知り、早速ダウンロードさせていただきましたが、
現在EPGSTATION自体のBasic認証を使用しているため、
http://ID:PASS@アドレス:ポート
の形式で指定してみたものの、うまくいかないようです。
ご確認のほど、お願いいたします。

**Comment by advancedbear** [comment]
EPGStation側でBasicAuth認証を有効にした状態で確認しましたが、 `EPGStation URL` 欄に `http://username:password@192.168.xxx.xxx:8888/` の形式で動作しております。

ID/Passwordが正しいかどうか、ブラウザ経由で同形式のURLにアクセス可能かなどを確認いただきたいです。

**Comment by unicode45** [comment]
教えて頂いた通りに無事URL指定でBasic認証も通りました。
ありがとうございます。
